<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="Creating Modal Window with Bootstrap" />
	<title>软件学院论文盲审系统</title>
	<link rel="shortcut icon" href="/paperevalu/favicon.ico" type="image/x-icon" /><!--地址栏和标签上显示图标-->
	<!-- <link href="/paperevalu/static/css/bootstrap.min.css" rel="stylesheet" /> -->
	<link href="http://lib.sinaapp.com/js/bootstrap/latest/css/bootstrap.min.css" rel="stylesheet" /> 
	<!-- <link href="/paperevalu/static/css/index.css" rel="stylesheet" /> -->
	<link href="/paperevalu/static/css/home.css" rel="stylesheet" />
	<!-- <link href="/paperevalu/static/css/bootstrap2.min.css" rel="stylesheet" /> -->
	<script type="text/javascript" src="/paperevalu/static/js/jquery-2.0.3.js"></script>
   	<script type="text/javascript" src="/paperevalu/static/js/bootstrap.min.js"></script>
</head> 
<body> 